lang: ru-RU
encoding: utf-8

url: http://prog.msk.ru
title: Московский клуб программистов

permalink: pretty
highlighter: rouge
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-feed

paginate: 10
paginate_path: "blog/:num"

